# -*- coding: utf-8 -*-
"""Interactive burnout calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwpW7BJlzCaGTgUGYOVRlLQ5pMz4H8GX

### Install Required Libraries
"""

# Install required libraries
import subprocess
import sys

print("Installing required libraries...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "pandas", "numpy", "scikit-learn", "ipywidgets", "IPython"])

print("Libraries installed!\n")

"""### Imports"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import warnings
warnings.filterwarnings('ignore')

print("Every data is imported!\n")

"""### Sample Data"""

import pandas as pd
import os

# Load the main dataset
dataset = pd.read_csv('/content/expanded_sleep_health_dataset.csv')

# Add a 'Name' column to the original dataset, initialized to None
if 'Name' not in dataset.columns:
    dataset['Name'] = None

new_registrations_file = 'new_registrations.csv'
if os.path.exists(new_registrations_file):
    new_data_df = pd.read_csv(new_registrations_file)

    # Ensure 'Name' column exists in new_data_df
    if 'Name' not in new_data_df.columns:
        new_data_df['Name'] = None

    # Align columns before concatenation: add missing columns to each df, fill with NaN
    all_cols = list(set(dataset.columns) | set(new_data_df.columns))
    for col in all_cols:
        if col not in dataset.columns:
            dataset[col] = None
        if col not in new_data_df.columns:
            new_data_df[col] = None

    # Reorder columns to match for proper concatenation
    new_data_df = new_data_df[dataset.columns]

    # Concatenate the original dataset with new registrations
    combined_dataset = pd.concat([dataset, new_data_df], ignore_index=True)

    # Drop duplicates based on 'Person ID', keeping the last entry (which would be from new_registrations if ID overlaps)
    dataset = combined_dataset.drop_duplicates(subset=['Person ID'], keep='last')

# Robustly handle potential None/NaN values in key categorical columns after loading/concatenation
# This ensures consistency before feature preparation and encoding
for col in ['Gender', 'BMI Category', 'Occupation']:
    if col in dataset.columns:
        # Convert actual None/NaN to 'Unknown', then stringify, then replace 'None' string/empty string to 'Unknown'
        dataset[col] = dataset[col].fillna('Unknown').astype(str).replace('None', 'Unknown').replace('', 'Unknown')
if 'Sleep Disorder' in dataset.columns:
    # For Sleep Disorder, 'None' is a valid category, so only map NaN/empty to 'Unknown'
    dataset['Sleep Disorder'] = dataset['Sleep Disorder'].fillna('Unknown').astype(str).replace('', 'Unknown')

# Handle potential NaN values in numerical columns used for burnout risk calculation
numerical_cols_for_burnout = ['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
                              'Stress Level', 'Heart Rate', 'Daily Steps']
for col in numerical_cols_for_burnout:
    if col in dataset.columns:
        # Convert to numeric, coerce errors to NaN, then fill NaN with 0
        dataset[col] = pd.to_numeric(dataset[col], errors='coerce').fillna(0)

print("=" * 60)
print("BURNOUT RISK ASSESSMENT - INTERACTIVE TOOL")
print("=" * 60)
print(f"\n✓ Loaded {len(dataset)} records from CSV file (including new registrations)\n")

"""### Data Preparation Functions"""

def prepare_features(df):
    """Prepare features for modeling"""
    df_processed = df.copy()

    # Parse Blood Pressure
    df_processed[['Systolic BP', 'Diastolic BP']] = df_processed['Blood Pressure'].str.split('/', expand=True).astype(float)

    # Encode categorical variables

    # Gender: Define all possible categories explicitly for robust fitting
    le_gender = LabelEncoder()
    all_genders = ['Male', 'Female', 'Unknown']
    le_gender.fit(all_genders) # Fit on comprehensive set

    # Process Gender column: convert to string, replace 'None' (string) with 'Unknown', handle empty strings and NaNs
    df_processed['Gender'] = df_processed['Gender'].astype(str).replace('None', 'Unknown').replace('', 'Unknown').fillna('Unknown')
    df_processed['Gender'] = le_gender.transform(df_processed['Gender'])

    # BMI Category: Define all possible categories explicitly for robust fitting
    le_bmi = LabelEncoder()
    all_bmi_categories = ['Underweight', 'Normal', 'Overweight', 'Obese', 'Unknown']
    le_bmi.fit(all_bmi_categories) # Fit on comprehensive set

    # Process BMI Category column: convert to string, replace 'None' (string) with 'Unknown', handle empty strings and NaNs
    df_processed['BMI Category'] = df_processed['BMI Category'].astype(str).replace('None', 'Unknown').replace('', 'Unknown').fillna('Unknown')
    df_processed['BMI Category'] = le_bmi.transform(df_processed['BMI Category'])

    # Sleep Disorder: Define all possible categories explicitly for robust fitting
    le_sleep = LabelEncoder()
    # 'None' is a valid category. Replace empty string/NaN with 'Unknown', but preserve 'None' string.
    all_sleep_disorders = ['None', 'Insomnia', 'Sleep Apnea', 'Restless Leg Syndrome', 'Narcolepsy', 'Unknown']
    le_sleep.fit(all_sleep_disorders) # Fit on comprehensive set

    # Process Sleep Disorder column: convert to string, replace empty string/NaN with 'Unknown'
    df_processed['Sleep Disorder'] = df_processed['Sleep Disorder'].astype(str).replace('', 'Unknown').fillna('Unknown')
    df_processed['Sleep Disorder'] = le_sleep.transform(df_processed['Sleep Disorder'])

    # Occupation: Convert to string, replace 'None' with 'Unknown', empty string with 'Unknown', fill NaNs with 'Unknown'.
    df_processed['Occupation'] = df_processed['Occupation'].astype(str).replace('None', 'Unknown').replace('', 'Unknown').fillna('Unknown')
    df_processed = pd.get_dummies(df_processed, columns=['Occupation'], prefix='Occ', drop_first=True)

    target = df_processed['Burnout Risk']
    features = df_processed.drop(['Person ID', 'Blood Pressure', 'Burnout Risk'], axis=1)

    # Normalize
    scaler = StandardScaler()
    numerical_cols = ['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
                     'Stress Level', 'Heart Rate', 'Daily Steps', 'Systolic BP', 'Diastolic BP']
    features[numerical_cols] = scaler.fit_transform(features[numerical_cols])

    return features, target, scaler, le_gender, le_bmi, le_sleep

def create_burnout_target(df):
    """Create burnout target variable based on 8 criteria"""
    conditions = [
        df['Stress Level'] >= 7,
        df['Quality of Sleep'] <= 5,
        df['Sleep Duration'] < 6.5,
        df['Physical Activity Level'] < 30,
        df['Heart Rate'] > 90,
        df['Sleep Disorder'] != 'None', # This condition checks for 'None' as a string
        df['BMI Category'].isin(['Overweight', 'Obese']),
        df['Daily Steps'] < 5000
    ]
    risk_count = sum(conditions)
    df['Burnout Risk'] = (risk_count >= 3).astype(int)
    return df

"""### Prepare Data (Execution)"""

dataset = create_burnout_target(dataset)
X, y, scaler, le_gender, le_bmi, le_sleep = prepare_features(dataset)

print("✓ Features prepared")
print(f"✓ Total features: {X.shape[1]}\n")

"""### Train Models"""

print("Training ML models...")

models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    'XGBoost': XGBClassifier(n_estimators=100, random_state=42, verbosity=0)
}

for name, model in models.items():
    model.fit(X, y)
    score = model.score(X, y)
    print(f"  ✓ {name}: {score:.1%}")

print("\n✓ Models trained and ready!\n")

"""### Prediction Function"""

def predict_burnout(person_data):
    """Predict burnout risk for a person"""
    person_df = pd.DataFrame([person_data])
    person_processed = person_df.copy()

    # Parse Blood Pressure
    person_processed[['Systolic BP', 'Diastolic BP']] = person_processed['Blood Pressure'].str.split('/', expand=True).astype(float)

    # Encode categorical
    # Gender: Convert to string, replace 'None' (string) with 'Unknown', empty string with 'Unknown', fill NaNs with 'Unknown'.
    person_processed['Gender'] = person_processed['Gender'].astype(str).replace('None', 'Unknown').replace('', 'Unknown').fillna('Unknown')
    person_processed['Gender'] = le_gender.transform(person_processed['Gender'])

    # BMI Category: Convert to string, replace 'None' (string) with 'Unknown', empty string with 'Unknown', fill NaNs with 'Unknown'.
    person_processed['BMI Category'] = person_processed['BMI Category'].astype(str).replace('None', 'Unknown').replace('', 'Unknown').fillna('Unknown')
    person_processed['BMI Category'] = le_bmi.transform(person_processed['BMI Category'])

    # Sleep Disorder: Convert to string. 'None' is a valid category. Replace empty string/NaN with 'Unknown'.
    person_processed['Sleep Disorder'] = person_processed['Sleep Disorder'].astype(str).replace('', 'Unknown').fillna('Unknown')
    person_processed['Sleep Disorder'] = le_sleep.transform(person_processed['Sleep Disorder'])

    # Occupation: Convert to string, replace 'None' with 'Unknown', empty string with 'Unknown', fill NaNs with 'Unknown'.
    person_processed['Occupation'] = person_processed['Occupation'].astype(str).replace('None', 'Unknown').replace('', 'Unknown').fillna('Unknown')
    person_processed = pd.get_dummies(person_processed, columns=['Occupation'], prefix='Occ', drop_first=True)

    features = person_processed.drop(['Person ID', 'Blood Pressure'], axis=1)

    # Add missing columns (present in training data but not in current person's features)
    for col in X.columns:
        if col not in features.columns:
            features[col] = 0

    # Remove extra columns (present in current person's features but not in training data)
    # This handles new, unseen occupation categories by effectively dropping them
    extra_cols = [col for col in features.columns if col not in X.columns]
    if extra_cols:
        features = features.drop(columns=extra_cols)

    # Select features in correct order
    X_new = features[X.columns]

    # Normalize
    numerical_cols = ['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
                     'Stress Level', 'Heart Rate', 'Daily Steps', 'Systolic BP', 'Diastolic BP']
    X_new[numerical_cols] = scaler.transform(X_new[numerical_cols])

    # Get predictions
    predictions = {}
    for name, model in models.items():
        pred = model.predict(X_new.values)[0]
        pred_proba = model.predict_proba(X_new.values)[0][1]
        predictions[name] = {'prediction': int(pred), 'probability': float(pred_proba)}

    avg_prob = np.mean([p['probability'] for p in predictions.values()])
    return predictions, float(avg_prob)

"""### BMI Calculator"""

def calculate_bmi(height, weight, height_unit='cm', weight_unit='kg'):
    """Calculate BMI and return category"""
    # Convert to metric
    if height_unit == 'in':
        height = height * 2.54
    height_m = height / 100

    if weight_unit == 'lb':
        weight = weight * 0.453592

    # Calculate BMI
    bmi = weight / (height_m ** 2)

    # Determine category
    if bmi < 18.5:
        category = 'Underweight'
    elif bmi < 25:
        category = 'Normal'
    elif bmi < 30:
        category = 'Overweight'
    else:
        category = 'Obese'

    return round(bmi, 1), category

"""### UI Components: Header, Search and Results Display"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import warnings
warnings.filterwarnings('ignore')

# ==================== UI COMPONENTS ====================

def display_header():
    """Display app header"""
    display(HTML("""
    <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #1e293b; margin-bottom: 10px;">🔥 Burnout Risk Assessment</h1>
        <p style="color: #64748b; font-size: 14px;">Analyze your burnout risk based on lifestyle and health factors</p>
    </div>
    """))

def display_search_interface():
    """Display search interface"""
    display(HTML("<h2 style='color: #1e293b; margin-bottom: 20px;'>Search by Person ID or Name</h2>"))

    search_input = widgets.Text(
        description='Person ID or Name:',
        placeholder='e.g., 5 or John Doe',
        style={'description_width': '150px'},
        layout=widgets.Layout(width='350px')
    )

    search_button = widgets.Button(
        description='Search',
        button_style='info',
        layout=widgets.Layout(width='100px')
    )

    output = widgets.Output()

    def on_search_click(b):
        with output:
            clear_output(wait=True)
            search_query = search_input.value

            person = None
            try:
                # Try searching by Person ID first (if input is numeric)
                person_id = int(search_query)
                mask = dataset['Person ID'] == person_id
                if mask.any():
                    person = dataset[mask].iloc[0]
            except ValueError:
                # If not a number, try searching by Name
                # Ensure 'Name' column exists in dataset before searching
                if 'Name' in dataset.columns:
                    mask = dataset['Name'].astype(str).str.lower() == search_query.lower()
                    if mask.any():
                        person = dataset[mask].iloc[0]

            if person is not None:
                display_person_results(person)
            else:
                display(HTML(f"<p style='color: #dc2626;'>❌ Person '{search_query}' not found</p>"))

                # Display register button if person not found
                register_button_not_found = widgets.Button(
                    description='Register New',
                    button_style='warning',
                    layout=widgets.Layout(width='120px')
                )

                def on_register_click(b):
                    with output:
                        clear_output(wait=True)
                        display_new_registration_modal() # Call the new modal function

                register_button_not_found.on_click(on_register_click)
                display(register_button_not_found)

    search_button.on_click(on_search_click)

    display(widgets.HBox([search_input, search_button]))
    display(output)

def get_indicator_dot(metric, value):
    """Returns an HTML span with a colored dot based on metric value"""
    color = 'grey' # Default color

    if metric == 'Sleep Duration':
        if 7.0 <= value <= 9.0:
            color = '#16a34a' # Green
        elif 6.5 <= value < 7.0 or value > 9.0:
            color = '#f97316' # Orange
        else:
            color = '#dc2626' # Red
    elif metric == 'Quality of Sleep':
        if value >= 7:
            color = '#16a34a'
        elif value >= 5:
            color = '#f97316'
        else:
            color = '#dc2626'
    elif metric == 'Stress Level':
        if value <= 4:
            color = '#16a34a'
        elif value <= 6:
            color = '#f97316'
        else:
            color = '#dc2626'
    elif metric == 'Heart Rate':
        if 60 <= value <= 100:
            color = '#16a34a'
        elif value > 100 or value < 60:
            color = '#f97316' # Moderate risk if slightly out of range
        else:
            color = '#dc2626' # High risk if significantly out of range (though not explicitly covered by simple ranges here)
    elif metric == 'Physical Activity Level':
        if value >= 60:
            color = '#16a34a'
        elif value >= 30:
            color = '#f97316'
        else:
            color = '#dc2626'
    elif metric == 'Daily Steps':
        if value >= 7500:
            color = '#16a34a'
        elif value >= 5000:
            color = '#f97316'
        else:
            color = '#dc2626'

    return f"<span style='height: 10px; width: 10px; background-color: {color}; border-radius: 50%; display: inline-block; margin-left: 8px;'></span>"

def display_person_results(person):
    """Display results for a person"""
    predictions, avg_prob = predict_burnout(person)

    # Calculate risk factors
    conditions = [
        person['Stress Level'] >= 7,
        person['Quality of Sleep'] <= 5,
        person['Sleep Duration'] < 6.5,
        person['Physical Activity Level'] < 30,
        person['Heart Rate'] > 90,
        person['Sleep Disorder'] != 'None',
        person['BMI Category'] in ['Overweight', 'Obese'],
        person['Daily Steps'] < 5000
    ]
    risk_factors = sum(conditions)

    # Determine risk level
    if avg_prob >= 0.7:
        risk_label = '🔴 HIGH RISK'
        risk_color = '#dc2626'
    elif avg_prob >= 0.3:
        risk_label = '🟡 MODERATE RISK'
        risk_color = '#f97316'
    else:
        risk_label = '🟢 LOW RISK'
        risk_color = '#16a34a'

    # Get Name for display, default to 'Person ID' if Name is not available or None
    person_id = int(person['Person ID'])
    person_name = person.get('Name')

    if pd.isna(person_name) or person_name is None:
        person_header_display = f"Person ID: {person_id}"
    else:
        person_header_display = f"{person_name} (ID: {person_id})"

    # Display results
    html = f"""
    <div style="background: white; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <h3 style="color: #1e293b;">{person_header_display}</h3>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0;">
            <div><strong>Gender:</strong> {person['Gender']}</div>
            <div><strong>Age:</strong> {int(person['Age'])} years</div>
            <div><strong>Occupation:</strong> {person['Occupation']}</div>
            <div><strong>BMI:</strong> {person['BMI Category']}</div>
        </div>

        <div style="background: #f8fafc; border-radius: 10px; padding: 20px; text-align: center; margin: 20px 0;">
            <h2 style="color: {risk_color}; margin: 0;">{risk_label}</h2>
            <p style="font-size: 36px; font-weight: bold; color: {risk_color}; margin: 10px 0;">{round(avg_prob * 100)}%</p>
            <p style="color: #64748b; margin: 0;">Based on {risk_factors} risk factor(s)</p>
        </div>

        <h4 style="color: #1e293b; margin-top: 20px;">Health Metrics:</h4>
        <table style="width: 100%; border-collapse: collapse;">
    """

    metrics = [
        ('Sleep Duration', person['Sleep Duration'], f"{person['Sleep Duration']} hours"),
        ('Quality of Sleep', person['Quality of Sleep'], f"{int(person['Quality of Sleep'])}/10"),
        ('Stress Level', person['Stress Level'], f"{int(person['Stress Level'])}/10"),
        ('Physical Activity Level', person['Physical Activity Level'], f"{int(person['Physical Activity Level'])} min/day"),
        ('Daily Steps', person['Daily Steps'], f"{int(person['Daily Steps'])} spacers"),
        ('Heart Rate', person['Heart Rate'], f"{int(person['Heart Rate'])} bpm")
    ]

    for label, value_for_dot, display_value in metrics:
        dot = get_indicator_dot(label, value_for_dot)
        html += f"<tr><td style='padding: 8px; border-bottom: 1px solid #e2e8f0;'><strong>{label}:</strong></td><td style='padding: 8px; border-bottom: 1px solid #e2e8f0;'>{display_value}{dot}</td></tr>"

    html += """</table>

        <div style="background: #e0f2fe; border-left: 5px solid #0ea5e9; padding: 15px; margin-top: 30px; border-radius: 6px;">
            <p style="color: #0c4a6e; font-size: 15px; margin: 0;">Do you want more information or help to reduce the chance of burnout?</p>
            <p style="margin: 10px 0 0 0;"><a href="https://www.healthhub.sg/" target="_blank" style="color: #0ea5e9; text-decoration: none; font-weight: bold;">Visit HealthHub.sg for more information</a></p>
        </div>

    </div>"""

    display(HTML(html))

"""### UI Components: Registration Form"""

def display_registration_form():
    """Display registration form"""
    display(HTML("<h2 style='color: #1e293b; margin-bottom: 20px;'>Register Your Data</h2>"))

    # Personal Info
    gender = widgets.Dropdown(
        options=['', 'Male', 'Female'],
        description='Gender:',
        layout=widgets.Layout(width='200px')
    )

    age = widgets.IntSlider(
        value=30,
        min=18,
        max=80,
        description='Age:',
        layout=widgets.Layout(width='250px')
    )

    occupation = widgets.Dropdown(
        options=[''] + sorted(dataset['Occupation'].unique().tolist()),
        description='Occupation:',
        layout=widgets.Layout(width='300px')
    )

    # Sleep
    sleep_duration = widgets.FloatSlider(
        value=7.0,
        min=4.5,
        max=10,
        step=0.5,
        description='Sleep (h):',
        layout=widgets.Layout(width='250px')
    )

    sleep_quality = widgets.IntSlider(
        value=7,
        min=1,
        max=10,
        description='Sleep Quality:',
        layout=widgets.Layout(width='250px')
    )

    sleep_disorder = widgets.Dropdown(
        options=['None', 'Insomnia', 'Sleep Apnea', 'Restless Leg Syndrome', 'Narcolepsy'],
        description='Sleep Disorder:',
        layout=widgets.Layout(width='300px')
    )

    # Activity
    activity = widgets.IntSlider(
        value=60,
        min=0,
        max=180,
        step=10,
        description='Activity (min):',
        layout=widgets.Layout(width='250px')
    )

    steps = widgets.IntSlider(
        value=8000,
        min=1000,
        max=20000,
        step=1000,
        description='Daily Steps:',
        layout=widgets.Layout(width='250px')
    )

    stress = widgets.IntSlider(
        value=5,
        min=1,
        max=10,
        description='Stress Level:',
        layout=widgets.Layout(width='250px')
    )

    # Health
    bmi_category = widgets.Dropdown(
        options=['', 'Underweight', 'Normal', 'Overweight', 'Obese'],
        description='BMI Category:',
        layout=widgets.Layout(width='250px')
    )

    # BMI Calculator
    height = widgets.FloatText(value=170, description='Height:', layout=widgets.Layout(width='150px'))
    height_unit = widgets.Dropdown(options=['cm', 'in'], description='', layout=widgets.Layout(width='70px'))
    weight = widgets.FloatText(value=70, description='Weight:', layout=widgets.Layout(width='150px'))
    weight_unit = widgets.Dropdown(options=['kg', 'lb'], description='', layout=widgets.Layout(width='70px'))

    bmi_output = widgets.Output()

    def calculate_bmi_click(b):
        with bmi_output:
            clear_output()
            h = height.value
            w = weight.value
            h_unit = height_unit.value
            w_unit = weight_unit.value

            bmi, category = calculate_bmi(h, w, h_unit, w_unit)
            bmi_category.value = category
            display(HTML(f"<p style='color: #16a34a;'>✓ BMI: <strong>{bmi}</strong> ({category})</p>"))

    bmi_button = widgets.Button(description='Calculate BMI', button_style='info')
    bmi_button.on_click(calculate_bmi_click)

    heart_rate = widgets.IntSlider(
        value=75,
        min=40,
        max=120,
        description='Heart Rate:',
        layout=widgets.Layout(width='250px')
    )

    blood_pressure = widgets.Text(
        value='120/80',
        description='Blood Pressure:',
        placeholder='120/80',
        layout=widgets.Layout(width='250px')
    )

    # Submit button
    submit_button = widgets.Button(
        description='Calculate Risk',
        button_style='success',
        layout=widgets.Layout(width='150px')
    )

    result_output = widgets.Output()

    def on_submit_click(b):
        with result_output:
            clear_output(wait=True)

            missing_fields = []
            if not gender.value: missing_fields.append('Gender')
            if not occupation.value: missing_fields.append('Occupation')
            if not bmi_category.value: missing_fields.append('BMI Category')
            if not blood_pressure.value or not '/' in blood_pressure.value: missing_fields.append('Blood Pressure (format: XXX/YYY)')

            # Sliders (age, sleep_duration, sleep_quality, activity, steps, stress, heart_rate) always have a value,
            # but we can add checks for meaningful ranges if necessary. For now, assume a value exists.

            if missing_fields:
                display(HTML(f"<p style='color: #dc2626;'>❌ Vul de volgende verplichte velden in: {', '.join(missing_fields)}</p>"))
                return

            # Create data
            person_data = {
                'Person ID': int(dataset['Person ID'].max()) + 1,
                'Gender': gender.value,
                'Age': age.value,
                'Occupation': occupation.value,
                'Sleep Duration': sleep_duration.value,
                'Quality of Sleep': sleep_quality.value,
                'Physical Activity Level': activity.value,
                'Stress Level': stress.value,
                'BMI Category': bmi_category.value,
                'Blood Pressure': blood_pressure.value,
                'Heart Rate': heart_rate.value,
                'Daily Steps': steps.value,
                'Sleep Disorder': sleep_disorder.value
            }

            display_person_results(pd.Series(person_data))

    submit_button.on_click(on_submit_click)

    # Display form
    display(HTML("<h4>Personal Information</h4>"))
    display(widgets.HBox([gender, age]))
    display(occupation)

    display(HTML("<h4>Sleep & Rest</h4>"))
    display(sleep_duration)
    display(sleep_quality)
    display(sleep_disorder)

    display(HTML("<h4>Activity & Stress</h4>"))
    display(activity)
    display(steps)
    display(stress)

    display(HTML("<h4>Health Metrics</h4>"))
    display(HTML("<p><strong>BMI Calculator:</strong></p>"))
    display(widgets.HBox([height, height_unit]))
    display(widgets.HBox([weight, weight_unit]))
    display(widgets.HBox([bmi_button]))
    display(bmi_output)

    display(bmi_category)
    display(heart_rate)
    display(blood_pressure)

    display(widgets.HBox([submit_button]))
    display(result_output)

"""### UI Components: New Registration Modal"""

def calculate_new_burnout_risk(stressniveau, werkuren, slaaproutine, werkdays):
    """Calculate burnout risk based on the new formula"""
    # Formula: (Stressniveau × 10) + (Werkuren × 5) - (Slaaproutine × 8) ÷ Werkdays
    # Ensure werkdays is not zero to avoid division by zero
    if werkdays == 0:
        return 100 # High risk if no workdays are specified or zero

    risk_score = (stressniveau * 10) + (werkuren * 5) - (slaaproutine * 8) / werkdays

    # Normalize to a percentage, capping at 0 and 100
    # Let's assume a baseline where 0 is very low risk and a high positive score is high risk.
    # This is a simplified mapping, might need adjustment based on desired distribution.
    min_score = 0 # Example baseline
    max_score = 200 # Example upper bound for risk score

    # Simple linear mapping to 0-100%
    percentage = max(0, min(100, (risk_score - min_score) / (max_score - min_score) * 100))
    return round(percentage, 1)

def display_new_registration_modal():
    """Display the new registration form as a modal-like interface with all health fields"""
    # Personal Info
    name_input = widgets.Text(
        description='Name:',
        placeholder='Full Name',
        layout=widgets.Layout(width='100%')
    )

    gender = widgets.Dropdown(
        options=['', 'Male', 'Female'],
        description='Gender:',
        layout=widgets.Layout(width='200px')
    )

    age = widgets.IntSlider(
        value=30,
        min=18,
        max=80,
        description='Age:',
        layout=widgets.Layout(width='250px')
    )

    occupation = widgets.Dropdown(
        options=[''] + sorted(dataset['Occupation'].unique().tolist()),
        description='Occupation:',
        layout=widgets.Layout(width='300px')
    )

    # Sleep
    sleep_duration = widgets.FloatSlider(
        value=7.0,
        min=4.5,
        max=10,
        step=0.5,
        description='Sleep (h):',
        layout=widgets.Layout(width='250px')
    )

    sleep_quality = widgets.IntSlider(
        value=7,
        min=1,
        max=10,
        description='Sleep Quality:',
        layout=widgets.Layout(width='250px')
    )

    sleep_disorder = widgets.Dropdown(
        options=['None', 'Insomnia', 'Sleep Apnea', 'Restless Leg Syndrome', 'Narcolepsy'],
        description='Sleep Disorder:',
        layout=widgets.Layout(width='300px')
    )

    # Activity
    activity = widgets.IntSlider(
        value=60,
        min=0,
        max=180,
        step=10,
        description='Activity (min):',
        layout=widgets.Layout(width='250px')
    )

    steps = widgets.IntSlider(
        value=8000,
        min=1000,
        max=20000,
        step=1000,
        description='Daily Steps:',
        layout=widgets.Layout(width='250px')
    )

    stress = widgets.IntSlider(
        value=5,
        min=1,
        max=10,
        description='Stress Level:',
        layout=widgets.Layout(width='250px')
    )

    # Health
    bmi_category = widgets.Dropdown(
        options=['', 'Underweight', 'Normal', 'Overweight', 'Obese'],
        description='BMI Category:',
        layout=widgets.Layout(width='250px')
    )

    # BMI Calculator
    height = widgets.FloatText(value=170, description='Height:', layout=widgets.Layout(width='150px'))
    height_unit = widgets.Dropdown(options=['cm', 'in'], description='', layout=widgets.Layout(width='70px'))
    weight = widgets.FloatText(value=70, description='Weight:', layout=widgets.Layout(width='150px'))
    weight_unit = widgets.Dropdown(options=['kg', 'lb'], description='', layout=widgets.Layout(width='70px'))

    bmi_output = widgets.Output()

    def calculate_bmi_click(b):
        with bmi_output:
            clear_output()
            h = height.value
            w = weight.value
            h_unit = height_unit.value
            w_unit = weight_unit.value

            bmi, category = calculate_bmi(h, w, h_unit, w_unit)
            bmi_category.value = category
            display(HTML(f"<p style='color: #16a34a;'>✓ BMI: <strong>{bmi}</strong> ({category})</p>"))

    bmi_button = widgets.Button(description='Calculate BMI', button_style='info')
    bmi_button.on_click(calculate_bmi_click)

    heart_rate = widgets.IntSlider(
        value=75,
        min=40,
        max=120,
        description='Heart Rate:',
        layout=widgets.Layout(width='250px')
    )

    blood_pressure = widgets.Text(
        value='120/80',
        description='Blood Pressure:',
        placeholder='120/80',
        layout=widgets.Layout(width='250px')
    )

    # Submit button
    submit_button = widgets.Button(
        description='Calculate Risk',
        button_style='success',
        layout=widgets.Layout(width='150px')
    )

    result_output = widgets.Output()

    def on_submit(b):
        with result_output:
            clear_output(wait=True)

            missing_fields = []
            if not name_input.value: missing_fields.append('Name')
            if not gender.value: missing_fields.append('Gender')
            if not occupation.value: missing_fields.append('Occupation')
            if not bmi_category.value: missing_fields.append('BMI Category')
            if not blood_pressure.value or not '/' in blood_pressure.value: missing_fields.append('Blood Pressure (format: XXX/YYY)')

            if missing_fields:
                display(HTML(f"<p style='color: #dc2626;'>❌ Vul de volgende verplichte velden in: {', '.join(missing_fields)}</p>"))
                return

            # Create data for prediction
            person_data_for_prediction = {
                'Person ID': int(dataset['Person ID'].max()) + 1,
                'Gender': gender.value,
                'Age': age.value,
                'Occupation': occupation.value,
                'Sleep Duration': sleep_duration.value,
                'Quality of Sleep': sleep_quality.value,
                'Physical Activity Level': activity.value,
                'Stress Level': stress.value,
                'BMI Category': bmi_category.value,
                'Blood Pressure': blood_pressure.value,
                'Heart Rate': heart_rate.value,
                'Daily Steps': steps.value,
                'Sleep Disorder': sleep_disorder.value
            }

            display_person_results(pd.Series(person_data_for_prediction))

            # Data for CSV saving (all fields)
            new_data_for_csv = {
                'Person ID': person_data_for_prediction['Person ID'],
                'Name': name_input.value,
                'Gender': person_data_for_prediction['Gender'],
                'Age': person_data_for_prediction['Age'],
                'Occupation': person_data_for_prediction['Occupation'],
                'Sleep Duration': person_data_for_prediction['Sleep Duration'],
                'Quality of Sleep': person_data_for_prediction['Quality of Sleep'],
                'Physical Activity Level': person_data_for_prediction['Physical Activity Level'],
                'Stress Level': person_data_for_prediction['Stress Level'],
                'BMI Category': person_data_for_prediction['BMI Category'],
                'Blood Pressure': person_data_for_prediction['Blood Pressure'],
                'Heart Rate': person_data_for_prediction['Heart Rate'],
                'Daily Steps': person_data_for_prediction['Daily Steps'],
                'Sleep Disorder': person_data_for_prediction['Sleep Disorder']
            }

            # Save to CSV
            csv_file = 'new_registrations.csv'
            try:
                new_df = pd.DataFrame([new_data_for_csv])
                if not os.path.exists(csv_file):
                    new_df.to_csv(csv_file, index=False)
                else:
                    new_df.to_csv(csv_file, mode='a', header=False, index=False)
                display(HTML(f"<p style='color: #16a34a;'>✓ Data opgeslagen in {csv_file}</p>"))
            except Exception as e:
                display(HTML(f"<p class='error-message'>❌ Fout bij opslaan van data: {e}</p>"))
                return



    submit_button.on_click(on_submit)

    def on_cancel(b):
        clear_output()
        display_search_interface()

    cancel_button = widgets.Button(description='Annuleren', button_style='danger', layout=widgets.Layout(width='120px'))
    cancel_button.on_click(on_cancel)

    # --- Construct the form widgets in a VBox --- START
    form_elements_vbox = widgets.VBox([
        widgets.HTML(
        """
        <style>
            .widget-label { font-weight: bold; margin-bottom: 5px; display: block; color: #334155; }
            .error-message { color: #dc2626; font-size: 12px; margin-top: 5px; display: block; }
            .modal-header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #eee; padding-bottom: 15px; margin-bottom: 20px; }
            .modal-header h2 { margin: 0; color: #1e293b; }
        </style>
        <div class='modal-header'><h2>Nieuwe Registratie</h2></div>
        """),
        widgets.VBox([
            name_input,
            widgets.HTML("<h4>Personal Information</h4>"),
            widgets.HBox([gender, age]),
            occupation,

            widgets.HTML("<h4>Sleep & Rest</h4>"),
            sleep_duration,
            sleep_quality,
            sleep_disorder,

            widgets.HTML("<h4>Activity & Stress</h4>"),
            activity,
            steps,
            stress,

            widgets.HTML("<h4>Health Metrics</h4>"),
            widgets.HTML("<p><strong>BMI Calculator:</strong></p>"),
            widgets.HBox([height, height_unit]),
            widgets.HBox([weight, weight_unit]),
            widgets.HBox([bmi_button]),
            bmi_output,

            bmi_category,
            heart_rate,
            blood_pressure,
        ], layout=widgets.Layout(margin='0 0 20px 0', width='100%')),
        result_output,
        widgets.HBox([submit_button, cancel_button], layout=widgets.Layout(justify_content='flex-end', width='100%'))
    ], layout=widgets.Layout(
        width='100%',
        background='white',
        padding='30px',
        border_radius='8px',
        max_width='600px',
        box_shadow='0 4px 8px rgba(0,0,0,0.1)',
        overflow_y='auto',
        max_height='90vh'
    ))

    modal_container = widgets.VBox(
        children=[form_elements_vbox],
        layout=widgets.Layout(
            position='fixed',
            top='0',
            left='0',
            width='100%',
            height='100%',
            display='flex',
            justify_content='center',
            align_items='center',
            background='rgba(0,0,0,0.5)',
            z_index='1000'
        )
    )

    clear_output(wait=True)
    display(modal_container)

import re
import os

"""### Main Application Logic"""

# ==================== MAIN APP ====================

print("=" * 60)
print("INTERACTIVE INTERFACE READY!")
print("=" * 60 + "\n")

display_header()
display_search_interface()